#!/usr/bin/env python3
"""Regenerates bba-lessons.js — the lesson titles of Le Lexique and El Léxico,
read from the two corpus.js files beside this repository. The teacher dashboard
uses it to print "U6.1 · Les grandes fêtes françaises" rather than "U6.1".
Run from the folder that holds the four site repositories."""
import re, json, os
here = os.path.dirname(os.path.abspath(__file__)); root = os.path.dirname(here)
out = {}
for lang, repo in (("FR", "A-Level-French-Edexcel-Vocab-training"), ("ES", "A-Level-Spanish-Edexcel-Vocabulary-training")):
    s = open(os.path.join(root, repo, "data", "corpus.js"), encoding="utf-8").read()
    d = {}
    for m in re.finditer(r'"lesson":\s*"([^"]+)",\s*"lessonTitle":\s*"((?:[^"\\]|\\.)*)"', s):
        d.setdefault(m.group(1), json.loads('"' + m.group(2) + '"'))
    out[lang] = d
js = ("/* Lesson titles for the two vocabulary sites, generated by build-lessons.py\n"
      "   from data/corpus.js in each. Regenerate when lists are added. */\n"
      "window.BBA_LESSONS = " + json.dumps(out, ensure_ascii=False) + ";\n")
open(os.path.join(here, "bba-lessons.js"), "w", encoding="utf-8").write(js)
print({k: len(v) for k, v in out.items()})
